import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ro";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.categories": "Categories",
    "nav.support": "Support",
    "nav.myStory": "My Story",
    "nav.contactUs": "Contact Us",
    "nav.explore": "Explore",
    "nav.admin": "Admin",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.changeLanguage": "Change language",
    "nav.userMenu": "User menu",
    "nav.openMenu": "Open menu",
    "nav.closeMenu": "Close menu",
    "hero.title": "The RoStory",
    "hero.subtitle": "A Visual Journey through Romanian Culture",
    "hero.badge": "Discover the Spirit of Romania",
    "categories.title": "Discover by Category",
    "articles.readMore": "Read Story",
    "articles.noArticles": "No stories found in this category.",
    "admin.title": "Admin Dashboard",
    "admin.addArticle": "Add New Story",
    "admin.addCategory": "Add New Category",
    "admin.addImage": "Add Image",
    "admin.tabs.articles": "Articles",
    "admin.tabs.myStories": "My Stories",
    "admin.tabs.stories": "Stories",
    "admin.tabs.categories": "Categories",
    "admin.tabs.categoriesShort": "Cats",
    "admin.tabs.users": "Users",
    "admin.tabs.permissions": "Permissions",
    "admin.tabs.permissionsShort": "Perms",
    "admin.access.restricted": "Access Restricted",
    "admin.access.noPermission": "You do not have permission to access the dashboard.",
    "admin.access.backHome": "Back to Home",
    "admin.permissions.heading": "Roles & Permissions Summary",
    "admin.permissions.subheading": "Review the access levels for each user role in The RoStory system.",
    "admin.permissions.role.guest": "Guest",
    "admin.permissions.role.guestDesc": "Unauthenticated visitors browsing the site.",
    "admin.permissions.role.reader": "Reader",
    "admin.permissions.role.readerDesc": "Default authenticated users who enjoy reading.",
    "admin.permissions.role.writer": "Writer",
    "admin.permissions.role.writerDesc": "Content creators who contribute stories.",
    "admin.permissions.role.admin": "Admin",
    "admin.permissions.role.adminDesc": "Full system administrators with complete control.",
    "admin.permissions.perm.browseCategories": "Browse Categories",
    "admin.permissions.perm.readPublished": "Read Published Stories",
    "admin.permissions.perm.supportContact": "Support Contact",
    "admin.permissions.perm.favoriteStories": "Favorite Stories",
    "admin.permissions.perm.createStories": "Create Stories",
    "admin.permissions.perm.manageSystem": "Manage System",
    "admin.permissions.perm.allGuestFeatures": "All Guest Features",
    "admin.permissions.perm.customProfile": "Custom Profile",
    "admin.permissions.perm.editStories": "Edit Stories",
    "admin.permissions.perm.allReaderFeatures": "All Reader Features",
    "admin.permissions.perm.editOwnStories": "Edit Own Stories",
    "admin.permissions.perm.publishStories": "Publish Stories",
    "admin.permissions.perm.manageCategories": "Manage Categories",
    "admin.permissions.perm.manageUsers": "Manage Users",
    "admin.permissions.perm.allWriterFeatures": "All Writer Features",
    "admin.permissions.perm.publishUnpublish": "Publish/Unpublish",
    "admin.permissions.perm.deleteAnyContent": "Delete Any Content",
    "admin.permissions.perm.changeRoles": "Change User Roles",
    "admin.permissions.enforcement.heading": "System Enforcement Logic",
    "admin.permissions.enforcement.frontend": "Frontend Guardrails",
    "admin.permissions.enforcement.backend": "Backend Enforcement",
    "admin.permissions.enforcement.frontend1": "Buttons for Admin actions are hidden from Writers/Readers.",
    "admin.permissions.enforcement.frontend2": "Draft status is automatically enforced for Writer submissions.",
    "admin.permissions.enforcement.frontend3": "Admin Dashboard is restricted to users with Admin or Writer roles.",
    "admin.permissions.enforcement.frontend4": "RLS (Row Level Security) filters favorites and profiles by owner ID.",
    "admin.permissions.enforcement.backend1": "Postgres RLS gates every read and write at the database level.",
    "admin.permissions.enforcement.backend2": "Edge Functions verify the JWT and admin role server-side.",
    "admin.permissions.enforcement.backend3": "Storage policies scope every upload to the user's own folder.",
    "admin.permissions.enforcement.backend4": "Self-publish is blocked: only writers/admins can author articles.",
    "admin.articles.heading": "Manage Stories",
    "admin.articles.searchHint": "Filter by title or status",
    "admin.articles.title": "Title",
    "admin.articles.category": "Category",
    "admin.articles.status": "Status",
    "admin.articles.date": "Date",
    "admin.articles.actions": "Actions",
    "admin.articles.uncategorized": "Uncategorized",
    "admin.articles.published": "Published",
    "admin.articles.draft": "Draft",
    "admin.articles.empty": "No stories found. Create your first one!",
    "admin.articles.newStory": "New Story",
    "admin.articles.editStory": "Edit Story",
    "admin.articles.editStoryDesc": "Update the details of the existing story.",
    "admin.articles.fillRequired": "Please fill required fields",
    "admin.articles.created": "Article added successfully",
    "admin.articles.updated": "Article updated successfully",
    "admin.articles.deleted": "Article deleted",
    "admin.articles.publishedToast": "Published",
    "admin.articles.unpublishedToast": "Unpublished",
    "admin.articles.adminOnlyPublish": "Only admins can publish articles",
    "admin.articles.errUpdate": "Error updating article",
    "admin.articles.errDelete": "Error deleting article",
    "admin.articles.errAdd": "Error adding article",
    "admin.articles.deleteTitle": "Delete this story?",
    "admin.articles.deleteDesc": "This will permanently remove the story. This action cannot be undone.",
    "admin.articles.publishImmediately": "Publish immediately",
    "admin.articles.titleEn": "Title (English)",
    "admin.articles.titleRo": "Title (Romanian)",
    "admin.articles.descEn": "Description (English)",
    "admin.articles.descRo": "Description (Romanian)",
    "admin.articles.mediaImageUrl": "Media URL (Image)",
    "admin.articles.mediaVideoUrl": "Video URL",
    "admin.articles.posterUrl": "Poster URL",
    "admin.articles.galleryImages": "Gallery images",
    "admin.articles.removeImage": "Remove image",
    "admin.articles.makeCover": "Make cover image",
    "admin.articles.update": "Update Story",
    "admin.articles.cancel": "Cancel",
    "admin.articles.typeSelect": "Choose story type",
    "admin.articles.typeSelectDesc": "Pick the format that fits your story best.",
    "admin.articles.typeText": "Text Story",
    "admin.articles.typeTextDesc": "Write a chapter-based story in both languages.",
    "admin.articles.typeVideo": "Video Story",
    "admin.articles.typeVideoDesc": "Showcase a short video about Romanian culture.",
    "admin.articles.typeCarousel": "Carousel Story",
    "admin.articles.typeCarouselDesc": "Tell a story through a sequence of images.",
    "admin.categories.heading": "Categories",
    "admin.categories.add": "Add New Category",
    "admin.categories.addBtn": "Add Category",
    "admin.categories.nameEn": "Name (EN)",
    "admin.categories.nameRo": "Name (RO)",
    "admin.categories.slug": "Slug",
    "admin.categories.slugPlaceholder": "e.g. historical-places",
    "admin.categories.slugHint": "Slug must be lowercase letters, numbers, and hyphens only (e.g. my-category)",
    "admin.categories.fillAll": "Please fill all fields",
    "admin.categories.added": "Category added successfully",
    "admin.categories.deleted": "Category deleted",
    "admin.categories.errAdd": "Error adding category",
    "admin.categories.errDelete": "Error deleting category",
    "admin.categories.deleteTitle": "Delete this category?",
    "admin.categories.deleteDesc": "Articles in this category will keep their content but lose the link. You can reassign them afterwards.",
    "admin.categories.confirm": "Delete",
    "admin.users.heading": "Manage Users",
    "admin.users.user": "User",
    "admin.users.email": "Email",
    "admin.users.role": "Role",
    "admin.users.joined": "Joined",
    "admin.users.anonymous": "Anonymous",
    "admin.users.empty": "No users found",
    "admin.users.previous": "Previous Page",
    "admin.users.next": "Next Page",
    "admin.users.errLoad": "Failed to load users",
    "admin.users.deleted": "User deleted",
    "admin.users.errDelete": "Error deleting user",
    "admin.users.deleteTitle": "Delete this user?",
    "admin.users.deleteDesc": "This will permanently remove the user account. This action cannot be undone.",
    "admin.users.deleteSelf": "You cannot delete yourself",
    "admin.users.roleUpdated": "User role updated",
    "admin.users.errRoleUpdate": "Error updating role",
    "admin.users.unverified": "Unverified",
    "admin.users.unverifiedTooltip": "This user signed up but never confirmed their email.",
    "admin.users.range": "Showing {start}-{end} of {total}",
    "admin.users.pageOnly": "Page {page}",
    "admin.common.delete": "Delete",
    "admin.common.cancel": "Cancel",
    "admin.common.save": "Save",
    "admin.common.notAuthenticated": "Not authenticated",
    "admin.common.imageUploaded": "Image uploaded successfully",
    "admin.common.errUpload": "Error uploading image",
    "admin.common.contentRequired": "A text story must have at least one chapter with content",
    "admin.articles.carouselRequiresImages": "A carousel story must have at least one image. Add an image or delete the story.",
    "admin.articles.errTitleTooLong": "Title exceeds {max} characters",
    "admin.articles.errContentTooLong": "Content exceeds {max} characters",
    "admin.articles.errLocationTooLong": "Location exceeds {max} characters",
    "admin.articles.errTooManyGalleryImages": "Too many gallery images (max {max})",
    "parchment.close": "Close Story",
    "parchment.theEnd": "The End",
    "home.randomTitle": "Feeling Adventurous?",
    "home.randomSubtitle": "Let us surprise you with a random story from our collection.",
    "home.randomButton": "Discover a Random Story",
    "contact.title": "Contact Us",
    "contact.subtitle": "Have a question or a story to share? We'd love to hear from you!",
    "contact.getInTouch": "Get in Touch",
    "contact.description": "Whether you have a question about our stories, want to suggest a new category, or just want to say hi, we're here for you.",
    "contact.formTitle": "Send us a Message",
    "contact.formDescription": "Fill out the form below and we'll get back to you as soon as possible.",
    "contact.name": "Name",
    "contact.namePlaceholder": "Your full name",
    "contact.email": "Email",
    "contact.emailLabel": "Email",
    "contact.emailPlaceholder": "your.email@example.com",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Tell us what's on your mind...",
    "contact.send": "Send Message",
    "contact.success": "Your message has been sent successfully!",
    "contact.error": "There was an error sending your message. Please try again.",
    "contact.followUs": "Follow Us",
    "contact.validation.name": "Name must be at least 2 characters.",
    "contact.validation.email": "Please enter a valid email address.",
    "contact.validation.message": "Message must be at least 10 characters.",
    "profile.title": "Your Profile",
    "profile.subtitle": "Manage your personal information and preferences",
    "profile.displayName": "Display Name",
    "profile.email": "Email Address",
    "profile.avatar": "Profile Picture",
    "profile.update": "Update Profile",
    "profile.updating": "Updating...",
    "profile.success": "Profile updated successfully!",
    "profile.error": "Failed to update profile. Please try again.",
    "nav.profile": "Profile",
    "nav.map": "Map",
    "location.label": "Location",
    "location.select": "Select a location",
    "map.zoomIn": "Zoom In",
    "map.zoomOut": "Zoom Out",
    "map.reset": "Reset map",
    "map.storiesIn": "Stories in",
    "map.noStories": "No stories in this location yet.",
    "map.clickToZoom": "Click to explore stories",
    "map.storyOne": "story",
    "map.storyMany": "stories",
    "map.legendTitle": "Stories per county",
    "map.legendNone": "None",
    "map.selectRegion": "Select a region",
    "map.selectRegionHint": "Click on any highlighted area of the map to discover local stories and traditions.",
    "share.title": "Share Story",
    "share.copyLink": "Copy Link",
    "share.copied": "Link copied to clipboard!",
    "share.facebook": "Share on Facebook",
    "share.twitter": "Share on X",
    "article.close": "Close article",
    "article.favorite": "Add to favorites",
    "article.unfavorite": "Remove from favorites",
    "related.title": "More stories you might like",
    "nav.favorites": "Favorites",
    "nav.dashboard": "Dashboard",
    "home.all": "All",
    "common.loading": "Loading...",
    "articles.photoCount": "Photos",
    "articles.videoBadge": "Video",
    "articles.carouselBadge": "Carousel",
    "auth.welcomeBack": "Welcome back!",
    "auth.loginFailed": "Login failed",
    "auth.accountCreatedVerify": "Account created! Please check your email to verify.",
    "auth.accountCreatedWelcome": "Account created! Welcome!",
    "auth.signupFailed": "Signup failed",
    "auth.signupGeneric": "If your email is available, we've sent a verification link.",
    "auth.passwordTooShort": "Password must be at least 8 characters.",
    "auth.googleFailed": "Google sign-in failed",
    "auth.resetLinkSent": "Password reset link sent to your email!",
    "auth.resetLinkFailed": "Failed to send reset link",
    "auth.passwordUpdated": "Password updated successfully! You can now login.",
    "auth.passwordResetFailed": "Failed to reset password",
    "auth.checkEmail": "Check your email",
    "auth.verificationSentTo": "We sent a verification link to",
    "auth.verifyEmailPrompt": "Please verify your email address to access all features.",
    "auth.didntGetEmail": "Didn't receive it? Check your spam folder first.",
    "auth.resendVerification": "Resend verification email",
    "auth.resendingVerification": "Sending...",
    "auth.resendVerificationSuccess": "Verification email sent — check your inbox.",
    "auth.resendVerificationFailed": "Could not resend the verification email. Please try again.",
    "auth.emailNotConfirmedTitle": "Please verify your email",
    "auth.emailNotConfirmedDesc": "We need to confirm this email address before you can sign in.",
    "auth.goHome": "Go to Home",
    "auth.resetPassword": "Reset Password",
    "auth.resetPasswordDesc": "Enter your email to receive a reset link",
    "auth.sendLink": "Send Link",
    "auth.backToLogin": "Back to Login",
    "auth.invalidResetLink": "Invalid Reset Link",
    "auth.invalidResetLinkDesc": "This password reset link is invalid or has expired.",
    "auth.invalidResetLinkHelp": "Please request a new password reset link from the login page.",
    "auth.requestNewLink": "Request New Link",
    "auth.newPassword": "New Password",
    "auth.newPasswordDesc": "Enter your new password",
    "auth.cancel": "Cancel",
    "auth.continueJourney": "Continue your journey",
    "auth.startStory": "Start your story",
    "auth.loginTab": "Login",
    "auth.signupTab": "Sign Up",
    "auth.displayName": "Display Name",
    "auth.password": "Password",
    "auth.showPassword": "Show password",
    "auth.hidePassword": "Hide password",
    "auth.forgotPassword": "Forgot password?",
    "auth.orContinueWith": "Or continue with",
    "auth.createAccount": "Create Account",
    "auth.agreement": "By continuing, you agree to explore the rich history and culture of Romania.",
    "search.placeholder": "Search stories...",
    "search.label": "Search",
    "search.close": "Close search",
    "search.noResults": "No stories found.",
    "search.searching": "Searching...",
    "search.unavailable": "Search unavailable — please try again later.",
  },
  ro: {
    "nav.home": "Acasă",
    "nav.categories": "Categorii",
    "nav.support": "Susține",
    "nav.myStory": "Povestea Mea",
    "nav.contactUs": "Contactează-ne",
    "nav.explore": "Explorează",
    "nav.admin": "Admin",
    "nav.login": "Autentificare",
    "nav.logout": "Deconectare",
    "nav.changeLanguage": "Schimbă limba",
    "nav.userMenu": "Meniu utilizator",
    "nav.openMenu": "Deschide meniul",
    "nav.closeMenu": "Închide meniul",
    "hero.title": "The RoStory",
    "hero.subtitle": "O călătorie vizuală prin cultura românească",
    "hero.badge": "Descoperă Spiritul României",
    "categories.title": "Descoperă pe categorii",
    "articles.readMore": "Citește povestea",
    "articles.noArticles": "Nu au fost găsite povești în această categorie.",
    "admin.title": "Panou Admin",
    "admin.addArticle": "Adaugă poveste nouă",
    "admin.addImage": "Adaugă imagine",
    "admin.addCategory": "Adaugă categorie nouă",
    "admin.tabs.articles": "Articole",
    "admin.tabs.myStories": "Poveștile mele",
    "admin.tabs.stories": "Povești",
    "admin.tabs.categories": "Categorii",
    "admin.tabs.categoriesShort": "Cat.",
    "admin.tabs.users": "Utilizatori",
    "admin.tabs.permissions": "Permisiuni",
    "admin.tabs.permissionsShort": "Permis.",
    "admin.access.restricted": "Acces restricționat",
    "admin.access.noPermission": "Nu ai permisiunea de a accesa panoul.",
    "admin.access.backHome": "Înapoi la pagina principală",
    "admin.permissions.heading": "Sumar roluri & permisiuni",
    "admin.permissions.subheading": "Verifică nivelurile de acces pentru fiecare rol în sistemul The RoStory.",
    "admin.permissions.role.guest": "Vizitator",
    "admin.permissions.role.guestDesc": "Vizitatori neautentificați care navighează pe site.",
    "admin.permissions.role.reader": "Cititor",
    "admin.permissions.role.readerDesc": "Utilizatori autentificați care citesc povești.",
    "admin.permissions.role.writer": "Scriitor",
    "admin.permissions.role.writerDesc": "Creatori de conținut care contribuie cu povești.",
    "admin.permissions.role.admin": "Administrator",
    "admin.permissions.role.adminDesc": "Administratori cu control complet asupra sistemului.",
    "admin.permissions.perm.browseCategories": "Răsfoiește categoriile",
    "admin.permissions.perm.readPublished": "Citește poveștile publicate",
    "admin.permissions.perm.supportContact": "Contact pentru asistență",
    "admin.permissions.perm.favoriteStories": "Povești favorite",
    "admin.permissions.perm.createStories": "Creează povești",
    "admin.permissions.perm.manageSystem": "Administrează sistemul",
    "admin.permissions.perm.allGuestFeatures": "Toate funcțiile pentru vizitatori",
    "admin.permissions.perm.customProfile": "Profil personalizat",
    "admin.permissions.perm.editStories": "Editează povești",
    "admin.permissions.perm.allReaderFeatures": "Toate funcțiile pentru cititori",
    "admin.permissions.perm.editOwnStories": "Editează propriile povești",
    "admin.permissions.perm.publishStories": "Publică povești",
    "admin.permissions.perm.manageCategories": "Administrează categoriile",
    "admin.permissions.perm.manageUsers": "Administrează utilizatorii",
    "admin.permissions.perm.allWriterFeatures": "Toate funcțiile pentru scriitori",
    "admin.permissions.perm.publishUnpublish": "Publică/Anulează publicarea",
    "admin.permissions.perm.deleteAnyContent": "Șterge orice conținut",
    "admin.permissions.perm.changeRoles": "Modifică rolurile utilizatorilor",
    "admin.permissions.enforcement.heading": "Logica aplicării regulilor",
    "admin.permissions.enforcement.frontend": "Restricții în interfață",
    "admin.permissions.enforcement.backend": "Aplicare în backend",
    "admin.permissions.enforcement.frontend1": "Butoanele pentru acțiunile de admin sunt ascunse pentru Scriitori/Cititori.",
    "admin.permissions.enforcement.frontend2": "Statutul de ciornă este aplicat automat pentru Scriitori.",
    "admin.permissions.enforcement.frontend3": "Panoul de admin este restricționat la utilizatorii cu rol de Admin sau Scriitor.",
    "admin.permissions.enforcement.frontend4": "RLS (Row Level Security) filtrează favoritele și profilurile după ID-ul proprietarului.",
    "admin.permissions.enforcement.backend1": "Postgres RLS controlează fiecare citire și scriere la nivel de bază de date.",
    "admin.permissions.enforcement.backend2": "Funcțiile Edge verifică JWT-ul și rolul de admin pe server.",
    "admin.permissions.enforcement.backend3": "Politicile de stocare limitează fiecare upload la folderul utilizatorului.",
    "admin.permissions.enforcement.backend4": "Auto-publicarea este blocată: doar scriitorii/admin-ii pot crea articole.",
    "admin.articles.heading": "Administrează poveștile",
    "admin.articles.searchHint": "Filtrează după titlu sau status",
    "admin.articles.title": "Titlu",
    "admin.articles.category": "Categorie",
    "admin.articles.status": "Status",
    "admin.articles.date": "Data",
    "admin.articles.actions": "Acțiuni",
    "admin.articles.uncategorized": "Necategorizat",
    "admin.articles.published": "Publicat",
    "admin.articles.draft": "Ciornă",
    "admin.articles.empty": "Nu s-au găsit povești. Creează prima ta poveste!",
    "admin.articles.newStory": "Poveste nouă",
    "admin.articles.editStory": "Editează povestea",
    "admin.articles.editStoryDesc": "Actualizează detaliile poveștii existente.",
    "admin.articles.fillRequired": "Te rugăm să completezi câmpurile obligatorii",
    "admin.articles.created": "Articol adăugat cu succes",
    "admin.articles.updated": "Articol actualizat cu succes",
    "admin.articles.deleted": "Articol șters",
    "admin.articles.publishedToast": "Publicat",
    "admin.articles.unpublishedToast": "Despublicat",
    "admin.articles.adminOnlyPublish": "Doar administratorii pot publica articole",
    "admin.articles.errUpdate": "Eroare la actualizarea articolului",
    "admin.articles.errDelete": "Eroare la ștergerea articolului",
    "admin.articles.errAdd": "Eroare la adăugarea articolului",
    "admin.articles.deleteTitle": "Ștergi această poveste?",
    "admin.articles.deleteDesc": "Aceasta va șterge permanent povestea. Acțiunea nu poate fi anulată.",
    "admin.articles.publishImmediately": "Publică imediat",
    "admin.articles.titleEn": "Titlu (Engleză)",
    "admin.articles.titleRo": "Titlu (Română)",
    "admin.articles.descEn": "Descriere (Engleză)",
    "admin.articles.descRo": "Descriere (Română)",
    "admin.articles.mediaImageUrl": "URL Media (Imagine)",
    "admin.articles.mediaVideoUrl": "URL Video",
    "admin.articles.posterUrl": "URL Poster",
    "admin.articles.galleryImages": "Imagini galerie",
    "admin.articles.removeImage": "Elimină imaginea",
    "admin.articles.makeCover": "Setează drept copertă",
    "admin.articles.update": "Actualizează povestea",
    "admin.articles.cancel": "Anulează",
    "admin.articles.typeSelect": "Alege tipul poveștii",
    "admin.articles.typeSelectDesc": "Alege formatul care se potrivește cel mai bine.",
    "admin.articles.typeText": "Poveste text",
    "admin.articles.typeTextDesc": "Scrie o poveste pe capitole în ambele limbi.",
    "admin.articles.typeVideo": "Poveste video",
    "admin.articles.typeVideoDesc": "Prezintă un scurt videoclip despre cultura română.",
    "admin.articles.typeCarousel": "Poveste tip carusel",
    "admin.articles.typeCarouselDesc": "Spune o poveste prin succesiune de imagini.",
    "admin.categories.heading": "Categorii",
    "admin.categories.add": "Adaugă categorie nouă",
    "admin.categories.addBtn": "Adaugă categorie",
    "admin.categories.nameEn": "Nume (EN)",
    "admin.categories.nameRo": "Nume (RO)",
    "admin.categories.slug": "Slug",
    "admin.categories.slugPlaceholder": "ex. locuri-istorice",
    "admin.categories.slugHint": "Slug-ul poate conține doar litere mici, cifre și cratime (ex. categoria-mea)",
    "admin.categories.fillAll": "Te rugăm să completezi toate câmpurile",
    "admin.categories.added": "Categorie adăugată cu succes",
    "admin.categories.deleted": "Categorie ștearsă",
    "admin.categories.errAdd": "Eroare la adăugarea categoriei",
    "admin.categories.errDelete": "Eroare la ștergerea categoriei",
    "admin.categories.deleteTitle": "Ștergi această categorie?",
    "admin.categories.deleteDesc": "Articolele din această categorie își păstrează conținutul, dar pierd legătura. Le poți reasigna ulterior.",
    "admin.categories.confirm": "Șterge",
    "admin.users.heading": "Administrează utilizatorii",
    "admin.users.user": "Utilizator",
    "admin.users.email": "Email",
    "admin.users.role": "Rol",
    "admin.users.joined": "Înregistrat",
    "admin.users.anonymous": "Anonim",
    "admin.users.empty": "Nu s-au găsit utilizatori",
    "admin.users.previous": "Pagina anterioară",
    "admin.users.next": "Pagina următoare",
    "admin.users.errLoad": "Eroare la încărcarea utilizatorilor",
    "admin.users.deleted": "Utilizator șters",
    "admin.users.errDelete": "Eroare la ștergerea utilizatorului",
    "admin.users.deleteTitle": "Ștergi acest utilizator?",
    "admin.users.deleteDesc": "Aceasta va șterge permanent contul. Acțiunea nu poate fi anulată.",
    "admin.users.deleteSelf": "Nu te poți șterge pe tine însuți",
    "admin.users.roleUpdated": "Rol actualizat",
    "admin.users.errRoleUpdate": "Eroare la actualizarea rolului",
    "admin.users.unverified": "Neverificat",
    "admin.users.unverifiedTooltip": "Acest utilizator s-a înregistrat dar nu și-a confirmat email-ul.",
    "admin.users.range": "Afișând {start}-{end} din {total}",
    "admin.users.pageOnly": "Pagina {page}",
    "admin.common.delete": "Șterge",
    "admin.common.cancel": "Anulează",
    "admin.common.save": "Salvează",
    "admin.common.notAuthenticated": "Neautentificat",
    "admin.common.imageUploaded": "Imagine încărcată cu succes",
    "admin.common.errUpload": "Eroare la încărcarea imaginii",
    "admin.common.contentRequired": "O poveste text trebuie să aibă cel puțin un capitol cu conținut",
    "admin.articles.carouselRequiresImages": "O poveste de tip carusel trebuie să aibă cel puțin o imagine. Adaugă o imagine sau șterge povestea.",
    "admin.articles.errTitleTooLong": "Titlul depășește {max} caractere",
    "admin.articles.errContentTooLong": "Conținutul depășește {max} caractere",
    "admin.articles.errLocationTooLong": "Locația depășește {max} caractere",
    "admin.articles.errTooManyGalleryImages": "Prea multe imagini în galerie (maxim {max})",
    "parchment.close": "Închide povestea",
    "parchment.theEnd": "Sfârșit",
    "home.randomTitle": "Te simți aventuros?",
    "home.randomSubtitle": "Lasă-ne să te surprindem cu o poveste aleatorie din colecția noastră.",
    "home.randomButton": "Descoperă o poveste aleatorie",
    "contact.title": "Contactează-ne",
    "contact.subtitle": "Ai o întrebare sau o poveste de împărtășit? Ne-ar plăcea să te ascultăm!",
    "contact.getInTouch": "Ia legătura cu noi",
    "contact.description": "Indiferent dacă ai o întrebare despre poveștile noastre, vrei să sugerezi o categorie nouă sau doar vrei să ne saluți, suntem aici pentru tine.",
    "contact.formTitle": "Trimite-ne un mesaj",
    "contact.formDescription": "Completează formularul de mai jos și îți vom răspunde cât mai curând posibil.",
    "contact.name": "Nume",
    "contact.namePlaceholder": "Numele tău complet",
    "contact.email": "Email",
    "contact.emailLabel": "Email",
    "contact.emailPlaceholder": "emailul.tau@exemplu.com",
    "contact.message": "Mesaj",
    "contact.messagePlaceholder": "Spune-ne ce ai pe suflet...",
    "contact.send": "Trimite Mesaj",
    "contact.success": "Mesajul tău a fost trimis cu succes!",
    "contact.error": "A apărut o eroare la trimiterea mesajului. Te rugăm să încerci din nou.",
    "contact.followUs": "Urmărește-ne",
    "contact.validation.name": "Numele trebuie să aibă cel puțin 2 caractere.",
    "contact.validation.email": "Te rugăm să introduci o adresă de email validă.",
    "contact.validation.message": "Mesajul trebuie să aibă cel puțin 10 caractere.",
    "profile.title": "Profilul Tău",
    "profile.subtitle": "Gestionează-ți informațiile personale și preferințele",
    "profile.displayName": "Nume Afișat",
    "profile.email": "Adresă de Email",
    "profile.avatar": "Poză de Profil",
    "profile.update": "Actualizează Profilul",
    "profile.updating": "Se actualizează...",
    "profile.success": "Profil actualizat cu succes!",
    "profile.error": "Actualizarea profilului a eșuat. Te rugăm să încerci din nou.",
    "nav.profile": "Profil",
    "nav.map": "Hartă",
    "location.label": "Locație",
    "location.select": "Selectează o locație",
    "map.zoomIn": "Mărește",
    "map.zoomOut": "Micșorează",
    "map.reset": "Resetează harta",
    "map.storiesIn": "Povești din",
    "map.noStories": "Nu există încă povești în această locație.",
    "map.clickToZoom": "Apasă pentru a explora poveștile",
    "map.storyOne": "poveste",
    "map.storyMany": "povești",
    "map.legendTitle": "Povești per județ",
    "map.legendNone": "Niciuna",
    "map.selectRegion": "Selectează o regiune",
    "map.selectRegionHint": "Apasă pe orice zonă evidențiată de pe hartă pentru a descoperi povești și tradiții locale.",
    "share.title": "Distribuie Povestea",
    "share.copyLink": "Copiază Link-ul",
    "share.copied": "Link copiat în clipboard!",
    "share.facebook": "Distribuie pe Facebook",
    "share.twitter": "Distribuie pe X",
    "article.close": "Închide articolul",
    "article.favorite": "Adaugă la favorite",
    "article.unfavorite": "Elimină din favorite",
    "related.title": "Mai multe povești care ți-ar putea plăcea",
    "nav.favorites": "Favorite",
    "nav.dashboard": "Panou control",
    "home.all": "Toate",
    "common.loading": "Se încarcă...",
    "articles.photoCount": "Fotografii",
    "articles.videoBadge": "Video",
    "articles.carouselBadge": "Carusel",
    "auth.welcomeBack": "Bine ai revenit!",
    "auth.loginFailed": "Autentificare eșuată",
    "auth.accountCreatedVerify": "Cont creat! Verifică-ți email-ul pentru confirmare.",
    "auth.accountCreatedWelcome": "Cont creat! Bine ai venit!",
    "auth.signupFailed": "Înregistrare eșuată",
    "auth.signupGeneric": "Dacă adresa de email este disponibilă, ți-am trimis un link de verificare.",
    "auth.passwordTooShort": "Parola trebuie să aibă cel puțin 8 caractere.",
    "auth.googleFailed": "Autentificarea cu Google a eșuat",
    "auth.resetLinkSent": "Link-ul de resetare a parolei a fost trimis pe email!",
    "auth.resetLinkFailed": "Trimiterea link-ului a eșuat",
    "auth.passwordUpdated": "Parola a fost actualizată cu succes! Te poți autentifica.",
    "auth.passwordResetFailed": "Resetarea parolei a eșuat",
    "auth.checkEmail": "Verifică-ți email-ul",
    "auth.verificationSentTo": "Am trimis un link de verificare la",
    "auth.verifyEmailPrompt": "Te rugăm să-ți verifici adresa de email pentru a accesa toate funcționalitățile.",
    "auth.didntGetEmail": "Nu l-ai primit? Verifică mai întâi folderul spam.",
    "auth.resendVerification": "Retrimite email-ul de verificare",
    "auth.resendingVerification": "Se trimite...",
    "auth.resendVerificationSuccess": "Email de verificare trimis — verifică-ți inbox-ul.",
    "auth.resendVerificationFailed": "Nu am putut retrimite email-ul. Te rugăm să încerci din nou.",
    "auth.emailNotConfirmedTitle": "Te rugăm să-ți verifici email-ul",
    "auth.emailNotConfirmedDesc": "Trebuie să confirmăm această adresă de email înainte să te poți autentifica.",
    "auth.goHome": "Mergi la Acasă",
    "auth.resetPassword": "Resetează Parola",
    "auth.resetPasswordDesc": "Introdu email-ul pentru a primi un link de resetare",
    "auth.sendLink": "Trimite Link",
    "auth.backToLogin": "Înapoi la Autentificare",
    "auth.invalidResetLink": "Link Invalid",
    "auth.invalidResetLinkDesc": "Acest link de resetare a parolei este invalid sau a expirat.",
    "auth.invalidResetLinkHelp": "Te rugăm să soliciți un nou link de resetare a parolei de pe pagina de autentificare.",
    "auth.requestNewLink": "Solicită Link Nou",
    "auth.newPassword": "Parolă Nouă",
    "auth.newPasswordDesc": "Introdu noua parolă",
    "auth.cancel": "Anulează",
    "auth.continueJourney": "Continuă-ți călătoria",
    "auth.startStory": "Începe-ți povestea",
    "auth.loginTab": "Autentificare",
    "auth.signupTab": "Înregistrare",
    "auth.displayName": "Nume afișat",
    "auth.password": "Parolă",
    "auth.showPassword": "Afișează parola",
    "auth.hidePassword": "Ascunde parola",
    "auth.forgotPassword": "Ai uitat parola?",
    "auth.orContinueWith": "Sau continuă cu",
    "auth.createAccount": "Creează Cont",
    "auth.agreement": "Continuând, ești de acord să explorezi istoria și cultura bogată a României.",
    "search.placeholder": "Caută povești...",
    "search.label": "Căutare",
    "search.close": "Închide căutarea",
    "search.noResults": "Nu s-au găsit povești.",
    "search.searching": "Se caută...",
    "search.unavailable": "Căutarea este indisponibilă — te rugăm să încerci din nou mai târziu.",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    try {
      const saved = window.localStorage.getItem("rostory_lang");
      return saved === "en" || saved === "ro" ? saved : "en";
    } catch {
      return "en";
    }
  });

  useEffect(() => {
    try {
      window.localStorage.setItem("rostory_lang", language);
    } catch {
      // Ignore browser storage restrictions
    }
    if (typeof document !== "undefined") {
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations["en"]] || '';
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
