import React, { createContext, useContext, useEffect, useCallback, useMemo } from "react";
import { localizedPath, stripLanguage, type Language } from "@/lib/locale";

/**
 * Union of every key in the EN dictionary. Typing t() against this catches
 * typo'd keys at compile time instead of silently rendering '' at runtime.
 */
export type TranslationKey = keyof typeof translations["en"];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.categories": "Categories",
    "nav.support": "Support",
    "nav.myStory": "My Story",
    "nav.contactUs": "Contact Us",
    "nav.admin": "Admin",
    "nav.logout": "Logout",
    "nav.openMenu": "Open menu",
    "nav.closeMenu": "Close menu",
    "articles.readMore": "Read Story",
    "articles.noArticles": "No stories found in this category.",
    "admin.title": "Admin Dashboard",
    "admin.addArticle": "Add New Story",
    "admin.tabs.articles": "Articles",
    "admin.tabs.myStories": "My Stories",
    "admin.tabs.stories": "Stories",
    "admin.tabs.categories": "Categories",
    "admin.tabs.categoriesShort": "Cats",
    "admin.tabs.users": "Users",
    "admin.tabs.storage": "Storage",
    "admin.tabs.permissions": "Permissions",
    "admin.tabs.permissionsShort": "Perms",
    "admin.access.restricted": "Access Restricted",
    "admin.access.noPermission": "You do not have permission to access the dashboard.",
    "admin.access.backHome": "Back to Home",
    "admin.permissions.heading": "Roles & Permissions Summary",
    "admin.permissions.subheading": "Review the access levels for each user role in The RoStory system.",
    "admin.permissions.role.guest": "Guest",
    "admin.permissions.role.guestDesc": "Unauthenticated visitors browsing the site.",
    "admin.permissions.role.reader": "Reader",
    "admin.permissions.role.readerDesc": "Default authenticated users who enjoy reading.",
    "admin.permissions.role.writer": "Writer",
    "admin.permissions.role.writerDesc": "Content creators who contribute stories.",
    "admin.permissions.role.admin": "Admin",
    "admin.permissions.role.adminDesc": "Full system administrators with complete control.",
    "admin.permissions.perm.browseCategories": "Browse Categories",
    "admin.permissions.perm.readPublished": "Read Published Stories",
    "admin.permissions.perm.supportContact": "Support Contact",
    "admin.permissions.perm.favoriteStories": "Favorite Stories",
    "admin.permissions.perm.createStories": "Create Stories",
    "admin.permissions.perm.manageSystem": "Manage System",
    "admin.permissions.perm.allGuestFeatures": "All Guest Features",
    "admin.permissions.perm.customProfile": "Custom Profile",
    "admin.permissions.perm.editStories": "Edit Stories",
    "admin.permissions.perm.allReaderFeatures": "All Reader Features",
    "admin.permissions.perm.editOwnStories": "Edit Own Stories",
    "admin.permissions.perm.publishStories": "Publish Stories",
    "admin.permissions.perm.manageCategories": "Manage Categories",
    "admin.permissions.perm.manageUsers": "Manage Users",
    "admin.permissions.perm.allWriterFeatures": "All Writer Features",
    "admin.permissions.perm.publishUnpublish": "Publish/Unpublish",
    "admin.permissions.perm.deleteAnyContent": "Delete Any Content",
    "admin.permissions.perm.changeRoles": "Change User Roles",
    "admin.permissions.enforcement.heading": "System Enforcement Logic",
    "admin.permissions.enforcement.frontend": "Frontend Guardrails",
    "admin.permissions.enforcement.backend": "Backend Enforcement",
    "admin.permissions.enforcement.frontend1": "Buttons for Admin actions are hidden from Writers/Readers.",
    "admin.permissions.enforcement.frontend2": "Draft status is automatically enforced for Writer submissions.",
    "admin.permissions.enforcement.frontend3": "Admin Dashboard is restricted to users with Admin or Writer roles.",
    "admin.permissions.enforcement.frontend4": "RLS (Row Level Security) filters favorites and profiles by owner ID.",
    "admin.permissions.enforcement.backend1": "Postgres RLS gates every read and write at the database level.",
    "admin.permissions.enforcement.backend2": "Edge Functions verify the JWT and admin role server-side.",
    "admin.permissions.enforcement.backend3": "Storage uploads are limited to writers/admins, scoped to their own folder, and restricted to an image/video allowlist.",
    "admin.permissions.enforcement.backend4": "Self-publish is blocked: only writers/admins can author articles.",
    "admin.storage.heading": "Storage Maintenance",
    "admin.storage.subheading": "Files no longer referenced by anything — article media that was replaced or deleted or left behind by an interrupted upload, and profile pictures replaced by a newer one. Both the articles and avatars buckets are scanned. Only files older than 24 hours are listed, so work in progress is never included.",
    "admin.storage.scan": "Scan storage",
    "admin.storage.scanning": "Scanning…",
    "admin.storage.purge": "Delete unreferenced files",
    "admin.storage.purging": "Deleting…",
    "admin.storage.clean": "Nothing to clean up — every file in both buckets is still referenced.",
    "admin.storage.found": "unreferenced files",
    "admin.storage.purged": "Files deleted:",
    "admin.storage.purgeTitle": "Delete unreferenced files?",
    "admin.storage.purgeDesc": "These files are not referenced by any story and will be permanently removed from storage. This cannot be undone.",
    "admin.storage.errScan": "Could not scan storage",
    "admin.storage.errPurge": "Could not delete the files",
    "admin.articles.heading": "Manage Stories",
    "admin.articles.title": "Title",
    "admin.articles.category": "Category",
    "admin.articles.status": "Status",
    "admin.articles.date": "Date",
    "admin.articles.actions": "Actions",
    "admin.articles.uncategorized": "Uncategorized",
    "admin.articles.published": "Published",
    "admin.articles.draft": "Draft",
    "admin.articles.empty": "No stories found. Create your first one!",
    "admin.articles.deleted": "Article deleted",
    "admin.articles.publishedToast": "Published",
    "admin.articles.unpublishedToast": "Unpublished",
    "admin.articles.adminOnlyPublish": "Only admins can publish articles",
    "admin.articles.errUpdate": "Error updating article",
    "admin.articles.errDelete": "Error deleting article",
    "admin.articles.deleteTitle": "Delete this story?",
    "admin.articles.deleteDesc": "This will permanently remove the story. This action cannot be undone.",
    "admin.articles.typeSelect": "Choose story type",
    "admin.articles.typeSelectDesc": "Pick the format that fits your story best.",
    "admin.articles.typeText": "Text Story",
    "admin.articles.typeVideo": "Video Story",
    "admin.articles.typeCarousel": "Carousel Story",
    "admin.categories.add": "Add New Category",
    "admin.categories.addBtn": "Add Category",
    "admin.categories.nameEn": "Name (EN)",
    "admin.categories.nameRo": "Name (RO)",
    "admin.categories.slug": "Slug",
    "admin.categories.slugPlaceholder": "e.g. historical-places",
    "admin.categories.slugHint": "Slug must be lowercase letters, numbers, and hyphens only (e.g. my-category)",
    "admin.categories.fillAll": "Please fill all fields",
    "admin.categories.added": "Category added successfully",
    "admin.categories.deleted": "Category deleted",
    "admin.categories.errAdd": "Error adding category",
    "admin.categories.errDelete": "Error deleting category",
    "admin.categories.deleteTitle": "Delete this category?",
    "admin.categories.deleteDesc": "Articles in this category will keep their content but lose the link. You can reassign them afterwards.",
    "admin.categories.confirm": "Delete",
    "admin.users.heading": "Manage Users",
    "admin.users.user": "User",
    "admin.users.email": "Email",
    "admin.users.role": "Role",
    "admin.users.joined": "Joined",
    "admin.users.anonymous": "Anonymous",
    "admin.users.empty": "No users found",
    "admin.users.previous": "Previous Page",
    "admin.users.next": "Next Page",
    "admin.users.errLoad": "Failed to load users",
    "admin.users.deleted": "User deleted",
    "admin.users.errDelete": "Error deleting user",
    "admin.users.deleteTitle": "Delete this user?",
    // Names the cascade explicitly. articles.user_id and comments.user_id are
    // ON DELETE CASCADE (migration 20260511000000), so deleting an account
    // also deletes everything that user published — including live stories.
    // The old copy said only "the user account", which understated it badly
    // for an irreversible action.
    "admin.users.deleteDesc": "This permanently deletes the account AND everything it published — all of this user's stories (including published ones), comments, and favorites. This cannot be undone.",
    "admin.users.deleteSelf": "You cannot delete yourself",
    "admin.users.roleUpdated": "User role updated",
    "admin.users.errRoleUpdate": "Error updating role",
    "admin.users.unverified": "Unverified",
    "admin.users.unverifiedTooltip": "This user signed up but never confirmed their email.",
    "admin.users.range": "Showing {start}-{end} of {total}",
    "admin.users.pageOnly": "Page {page}",
    "admin.common.delete": "Delete",
    "admin.common.cancel": "Cancel",
    "contact.title": "Contact Us",
    "contact.subtitle": "Have a question or a story to share? We'd love to hear from you!",
    "contact.namePlaceholder": "Your full name",
    "contact.emailPlaceholder": "your.email@example.com",
    "contact.messagePlaceholder": "Tell us what's on your mind...",
    "contact.success": "Your message has been sent successfully!",
    "contact.error": "There was an error sending your message. Please try again.",
    "contact.validation.name": "Name must be at least 2 characters.",
    "contact.validation.email": "Please enter a valid email address.",
    "contact.validation.message": "Message must be at least 10 characters.",
    "profile.title": "Your Profile",
    "profile.subtitle": "Manage your personal information and preferences",
    "profile.displayName": "Display Name",
    "profile.email": "Email Address",
    "profile.avatar": "Profile Picture",
    "profile.update": "Update Profile",
    "profile.updating": "Updating...",
    "profile.success": "Profile updated successfully!",
    "profile.error": "Failed to update profile. Please try again.",
    "nav.profile": "Profile",
    "nav.map": "Map",
    "location.label": "Location",
    "location.select": "Select a location",
    "map.zoomIn": "Zoom In",
    "map.zoomOut": "Zoom Out",
    "map.reset": "Reset map",
    "map.noStories": "No stories in this location yet.",
    "map.storyOne": "story",
    "map.storyMany": "stories",
    "map.legendNone": "None",
    "nav.favorites": "Favorites",
    "nav.dashboard": "Dashboard",
    "common.loading": "Loading...",
    "auth.welcomeBack": "Welcome back!",
    "auth.loginFailed": "Login failed. Please try again.",
    "auth.invalidCredentials": "Invalid email or password.",
    "auth.accountCreatedVerify": "Account created! Please check your email to verify.",
    "auth.accountCreatedWelcome": "Account created! Welcome!",
    "auth.signupFailed": "Signup failed",
    "auth.signupGeneric": "If your email is available, we've sent a verification link.",
    "auth.passwordTooShort": "Password must be at least 8 characters.",
    "auth.googleFailed": "Google sign-in failed",
    "auth.resetLinkSent": "Password reset link sent to your email!",
    "auth.resetLinkFailed": "Failed to send reset link",
    "auth.passwordUpdated": "Password updated successfully! You can now login.",
    "auth.passwordResetFailed": "Failed to reset password",
    "auth.rateLimited": "Too many attempts. Please wait a few minutes and try again.",
    "auth.passwordSameAsOld": "Your new password must be different from your current one.",
    "auth.checkEmail": "Check your email",
    "auth.verificationSentTo": "We sent a verification link to",
    "auth.didntGetEmail": "Didn't receive it? Check your spam folder first.",
    "auth.resendVerification": "Resend verification email",
    "auth.resendVerificationSuccess": "Verification email sent — check your inbox.",
    "auth.resendVerificationFailed": "Could not resend the verification email. Please try again.",
    "auth.emailNotConfirmedTitle": "Please verify your email",
    "auth.emailNotConfirmedDesc": "We need to confirm this email address before you can sign in.",
    "auth.goHome": "Go to homepage",
    "auth.resetPassword": "Reset Password",
    "auth.resetPasswordDesc": "Enter your email to receive a reset link",
    "auth.sendLink": "Send Link",
    "auth.backToLogin": "Back to Login",
    "auth.invalidResetLink": "Invalid Reset Link",
    "auth.invalidResetLinkDesc": "This password reset link is invalid or has expired.",
    "auth.invalidResetLinkHelp": "Please request a new password reset link from the login page.",
    "auth.requestNewLink": "Request New Link",
    "auth.newPassword": "New Password",
    "auth.newPasswordDesc": "Enter your new password",
    "auth.cancel": "Cancel",
    "auth.continueJourney": "Continue your journey",
    "auth.startStory": "Start your story",
    "auth.loginTab": "Login",
    "auth.signupTab": "Sign Up",
    "auth.displayName": "Display Name",
    "auth.password": "Password",
    "auth.showPassword": "Show password",
    "auth.hidePassword": "Hide password",
    "auth.forgotPassword": "Forgot password?",
    "auth.orContinueWith": "Or continue with",
    "auth.createAccount": "Create Account",
    "auth.agreement": "By continuing, you agree to explore the rich history and culture of Romania.",
  },
  ro: {
    "nav.home": "Acasă",
    "nav.categories": "Categorii",
    "nav.support": "Susține",
    "nav.myStory": "Povestea Mea",
    "nav.contactUs": "Contactează-ne",
    "nav.admin": "Admin",
    "nav.logout": "Deconectare",
    "nav.openMenu": "Deschide meniul",
    "nav.closeMenu": "Închide meniul",
    "articles.readMore": "Citește povestea",
    "articles.noArticles": "Nu au fost găsite povești în această categorie.",
    "admin.title": "Panou Admin",
    "admin.addArticle": "Adaugă poveste nouă",
    "admin.tabs.articles": "Articole",
    "admin.tabs.myStories": "Poveștile mele",
    "admin.tabs.stories": "Povești",
    "admin.tabs.categories": "Categorii",
    "admin.tabs.categoriesShort": "Cat.",
    "admin.tabs.users": "Utilizatori",
    "admin.tabs.storage": "Stocare",
    "admin.tabs.permissions": "Permisiuni",
    "admin.tabs.permissionsShort": "Permis.",
    "admin.access.restricted": "Acces restricționat",
    "admin.access.noPermission": "Nu ai permisiunea de a accesa panoul.",
    "admin.access.backHome": "Înapoi la pagina principală",
    "admin.permissions.heading": "Sumar roluri & permisiuni",
    "admin.permissions.subheading": "Verifică nivelurile de acces pentru fiecare rol în sistemul The RoStory.",
    "admin.permissions.role.guest": "Vizitator",
    "admin.permissions.role.guestDesc": "Vizitatori neautentificați care navighează pe site.",
    "admin.permissions.role.reader": "Cititor",
    "admin.permissions.role.readerDesc": "Utilizatori autentificați care citesc povești.",
    "admin.permissions.role.writer": "Scriitor",
    "admin.permissions.role.writerDesc": "Creatori de conținut care contribuie cu povești.",
    "admin.permissions.role.admin": "Administrator",
    "admin.permissions.role.adminDesc": "Administratori cu control complet asupra sistemului.",
    "admin.permissions.perm.browseCategories": "Răsfoiește categoriile",
    "admin.permissions.perm.readPublished": "Citește poveștile publicate",
    "admin.permissions.perm.supportContact": "Contact pentru asistență",
    "admin.permissions.perm.favoriteStories": "Povești favorite",
    "admin.permissions.perm.createStories": "Creează povești",
    "admin.permissions.perm.manageSystem": "Administrează sistemul",
    "admin.permissions.perm.allGuestFeatures": "Toate funcțiile pentru vizitatori",
    "admin.permissions.perm.customProfile": "Profil personalizat",
    "admin.permissions.perm.editStories": "Editează povești",
    "admin.permissions.perm.allReaderFeatures": "Toate funcțiile pentru cititori",
    "admin.permissions.perm.editOwnStories": "Editează propriile povești",
    "admin.permissions.perm.publishStories": "Publică povești",
    "admin.permissions.perm.manageCategories": "Administrează categoriile",
    "admin.permissions.perm.manageUsers": "Administrează utilizatorii",
    "admin.permissions.perm.allWriterFeatures": "Toate funcțiile pentru scriitori",
    "admin.permissions.perm.publishUnpublish": "Publică/Anulează publicarea",
    "admin.permissions.perm.deleteAnyContent": "Șterge orice conținut",
    "admin.permissions.perm.changeRoles": "Modifică rolurile utilizatorilor",
    "admin.permissions.enforcement.heading": "Logica aplicării regulilor",
    "admin.permissions.enforcement.frontend": "Restricții în interfață",
    "admin.permissions.enforcement.backend": "Aplicare în backend",
    "admin.permissions.enforcement.frontend1": "Butoanele pentru acțiunile de admin sunt ascunse pentru Scriitori/Cititori.",
    "admin.permissions.enforcement.frontend2": "Statutul de ciornă este aplicat automat pentru Scriitori.",
    "admin.permissions.enforcement.frontend3": "Panoul de admin este restricționat la utilizatorii cu rol de Admin sau Scriitor.",
    "admin.permissions.enforcement.frontend4": "RLS (Row Level Security) filtrează favoritele și profilurile după ID-ul proprietarului.",
    "admin.permissions.enforcement.backend1": "Postgres RLS controlează fiecare citire și scriere la nivel de bază de date.",
    "admin.permissions.enforcement.backend2": "Funcțiile Edge verifică JWT-ul și rolul de admin pe server.",
    "admin.permissions.enforcement.backend3": "Încărcările în stocare sunt permise doar scriitorilor/admin-ilor, limitate la folderul propriu și la o listă de tipuri imagine/video.",
    "admin.permissions.enforcement.backend4": "Auto-publicarea este blocată: doar scriitorii/admin-ii pot crea articole.",
    "admin.storage.heading": "Întreținerea stocării",
    "admin.storage.subheading": "Fișiere pe care nu le mai folosește nimic — media din articole înlocuită, ștearsă sau rămasă în urma unei încărcări întrerupte, și poze de profil înlocuite cu altele mai noi. Sunt scanate ambele bucket-uri, articles și avatars. Sunt listate doar fișierele mai vechi de 24 de ore, așa că materialele în lucru nu apar niciodată.",
    "admin.storage.scan": "Scanează stocarea",
    "admin.storage.scanning": "Se scanează…",
    "admin.storage.purge": "Șterge fișierele nefolosite",
    "admin.storage.purging": "Se șterge…",
    "admin.storage.clean": "Nimic de curățat — fiecare fișier din ambele bucket-uri este încă folosit.",
    "admin.storage.found": "fișiere nefolosite",
    "admin.storage.purged": "Fișiere șterse:",
    "admin.storage.purgeTitle": "Ștergi fișierele nefolosite?",
    "admin.storage.purgeDesc": "Aceste fișiere nu sunt folosite de nicio poveste și vor fi eliminate definitiv din stocare. Acțiunea nu poate fi anulată.",
    "admin.storage.errScan": "Scanarea stocării a eșuat",
    "admin.storage.errPurge": "Ștergerea fișierelor a eșuat",
    "admin.articles.heading": "Administrează poveștile",
    "admin.articles.title": "Titlu",
    "admin.articles.category": "Categorie",
    "admin.articles.status": "Status",
    "admin.articles.date": "Data",
    "admin.articles.actions": "Acțiuni",
    "admin.articles.uncategorized": "Necategorizat",
    "admin.articles.published": "Publicat",
    "admin.articles.draft": "Ciornă",
    "admin.articles.empty": "Nu s-au găsit povești. Creează prima ta poveste!",
    "admin.articles.deleted": "Articol șters",
    "admin.articles.publishedToast": "Publicat",
    "admin.articles.unpublishedToast": "Despublicat",
    "admin.articles.adminOnlyPublish": "Doar administratorii pot publica articole",
    "admin.articles.errUpdate": "Eroare la actualizarea articolului",
    "admin.articles.errDelete": "Eroare la ștergerea articolului",
    "admin.articles.deleteTitle": "Ștergi această poveste?",
    "admin.articles.deleteDesc": "Aceasta va șterge permanent povestea. Acțiunea nu poate fi anulată.",
    "admin.articles.typeSelect": "Alege tipul poveștii",
    "admin.articles.typeSelectDesc": "Alege formatul care se potrivește cel mai bine.",
    "admin.articles.typeText": "Poveste text",
    "admin.articles.typeVideo": "Poveste video",
    "admin.articles.typeCarousel": "Poveste tip carusel",
    "admin.categories.add": "Adaugă categorie nouă",
    "admin.categories.addBtn": "Adaugă categorie",
    "admin.categories.nameEn": "Nume (EN)",
    "admin.categories.nameRo": "Nume (RO)",
    "admin.categories.slug": "Slug",
    "admin.categories.slugPlaceholder": "ex. locuri-istorice",
    "admin.categories.slugHint": "Slug-ul poate conține doar litere mici, cifre și cratime (ex. categoria-mea)",
    "admin.categories.fillAll": "Te rugăm să completezi toate câmpurile",
    "admin.categories.added": "Categorie adăugată cu succes",
    "admin.categories.deleted": "Categorie ștearsă",
    "admin.categories.errAdd": "Eroare la adăugarea categoriei",
    "admin.categories.errDelete": "Eroare la ștergerea categoriei",
    "admin.categories.deleteTitle": "Ștergi această categorie?",
    "admin.categories.deleteDesc": "Articolele din această categorie își păstrează conținutul, dar pierd legătura. Le poți reasigna ulterior.",
    "admin.categories.confirm": "Șterge",
    "admin.users.heading": "Administrează utilizatorii",
    "admin.users.user": "Utilizator",
    "admin.users.email": "Email",
    "admin.users.role": "Rol",
    "admin.users.joined": "Înregistrat",
    "admin.users.anonymous": "Anonim",
    "admin.users.empty": "Nu s-au găsit utilizatori",
    "admin.users.previous": "Pagina anterioară",
    "admin.users.next": "Pagina următoare",
    "admin.users.errLoad": "Eroare la încărcarea utilizatorilor",
    "admin.users.deleted": "Utilizator șters",
    "admin.users.errDelete": "Eroare la ștergerea utilizatorului",
    "admin.users.deleteTitle": "Ștergi acest utilizator?",
    "admin.users.deleteDesc": "Aceasta șterge permanent contul ȘI tot ce a publicat — toate poveștile acestui utilizator (inclusiv cele publicate), comentariile și favoritele. Acțiunea nu poate fi anulată.",
    "admin.users.deleteSelf": "Nu te poți șterge pe tine însuți",
    "admin.users.roleUpdated": "Rol actualizat",
    "admin.users.errRoleUpdate": "Eroare la actualizarea rolului",
    "admin.users.unverified": "Neverificat",
    "admin.users.unverifiedTooltip": "Acest utilizator s-a înregistrat dar nu și-a confirmat email-ul.",
    "admin.users.range": "Afișând {start}-{end} din {total}",
    "admin.users.pageOnly": "Pagina {page}",
    "admin.common.delete": "Șterge",
    "admin.common.cancel": "Anulează",
    "contact.title": "Contactează-ne",
    "contact.subtitle": "Ai o întrebare sau o poveste de împărtășit? Ne-ar plăcea să te ascultăm!",
    "contact.namePlaceholder": "Numele tău complet",
    "contact.emailPlaceholder": "emailul.tau@exemplu.com",
    "contact.messagePlaceholder": "Spune-ne ce ai pe suflet...",
    "contact.success": "Mesajul tău a fost trimis cu succes!",
    "contact.error": "A apărut o eroare la trimiterea mesajului. Te rugăm să încerci din nou.",
    "contact.validation.name": "Numele trebuie să aibă cel puțin 2 caractere.",
    "contact.validation.email": "Te rugăm să introduci o adresă de email validă.",
    "contact.validation.message": "Mesajul trebuie să aibă cel puțin 10 caractere.",
    "profile.title": "Profilul Tău",
    "profile.subtitle": "Gestionează-ți informațiile personale și preferințele",
    "profile.displayName": "Nume Afișat",
    "profile.email": "Adresă de Email",
    "profile.avatar": "Poză de Profil",
    "profile.update": "Actualizează Profilul",
    "profile.updating": "Se actualizează...",
    "profile.success": "Profil actualizat cu succes!",
    "profile.error": "Actualizarea profilului a eșuat. Te rugăm să încerci din nou.",
    "nav.profile": "Profil",
    "nav.map": "Hartă",
    "location.label": "Locație",
    "location.select": "Selectează o locație",
    "map.zoomIn": "Mărește",
    "map.zoomOut": "Micșorează",
    "map.reset": "Resetează harta",
    "map.noStories": "Nu există încă povești în această locație.",
    "map.storyOne": "poveste",
    "map.storyMany": "povești",
    "map.legendNone": "Niciuna",
    "nav.favorites": "Favorite",
    "nav.dashboard": "Panou control",
    "common.loading": "Se încarcă...",
    "auth.welcomeBack": "Bine ai revenit!",
    "auth.loginFailed": "Autentificare eșuată. Te rugăm să încerci din nou.",
    "auth.invalidCredentials": "Email sau parolă incorecte.",
    "auth.accountCreatedVerify": "Cont creat! Verifică-ți email-ul pentru confirmare.",
    "auth.accountCreatedWelcome": "Cont creat! Bine ai venit!",
    "auth.signupFailed": "Înregistrare eșuată",
    "auth.signupGeneric": "Dacă adresa de email este disponibilă, ți-am trimis un link de verificare.",
    "auth.passwordTooShort": "Parola trebuie să aibă cel puțin 8 caractere.",
    "auth.googleFailed": "Autentificarea cu Google a eșuat",
    "auth.resetLinkSent": "Link-ul de resetare a parolei a fost trimis pe email!",
    "auth.resetLinkFailed": "Trimiterea link-ului a eșuat",
    "auth.passwordUpdated": "Parola a fost actualizată cu succes! Te poți autentifica.",
    "auth.passwordResetFailed": "Resetarea parolei a eșuat",
    "auth.rateLimited": "Prea multe încercări. Te rugăm să aștepți câteva minute.",
    "auth.passwordSameAsOld": "Noua parolă trebuie să fie diferită de cea curentă.",
    "auth.checkEmail": "Verifică-ți email-ul",
    "auth.verificationSentTo": "Am trimis un link de verificare la",
    "auth.didntGetEmail": "Nu l-ai primit? Verifică mai întâi folderul spam.",
    "auth.resendVerification": "Retrimite email-ul de verificare",
    "auth.resendVerificationSuccess": "Email de verificare trimis — verifică-ți inbox-ul.",
    "auth.resendVerificationFailed": "Nu am putut retrimite email-ul. Te rugăm să încerci din nou.",
    "auth.emailNotConfirmedTitle": "Te rugăm să-ți verifici email-ul",
    "auth.emailNotConfirmedDesc": "Trebuie să confirmăm această adresă de email înainte să te poți autentifica.",
    "auth.goHome": "Mergi la Acasă",
    "auth.resetPassword": "Resetează Parola",
    "auth.resetPasswordDesc": "Introdu email-ul pentru a primi un link de resetare",
    "auth.sendLink": "Trimite Link",
    "auth.backToLogin": "Înapoi la Autentificare",
    "auth.invalidResetLink": "Link Invalid",
    "auth.invalidResetLinkDesc": "Acest link de resetare a parolei este invalid sau a expirat.",
    "auth.invalidResetLinkHelp": "Te rugăm să soliciți un nou link de resetare a parolei de pe pagina de autentificare.",
    "auth.requestNewLink": "Solicită Link Nou",
    "auth.newPassword": "Parolă Nouă",
    "auth.newPasswordDesc": "Introdu noua parolă",
    "auth.cancel": "Anulează",
    "auth.continueJourney": "Continuă-ți călătoria",
    "auth.startStory": "Începe-ți povestea",
    "auth.loginTab": "Autentificare",
    "auth.signupTab": "Înregistrare",
    "auth.displayName": "Nume afișat",
    "auth.password": "Parolă",
    "auth.showPassword": "Afișează parola",
    "auth.hidePassword": "Ascunde parola",
    "auth.forgotPassword": "Ai uitat parola?",
    "auth.orContinueWith": "Sau continuă cu",
    "auth.createAccount": "Creează Cont",
    "auth.agreement": "Continuând, ești de acord să explorezi istoria și cultura bogată a României.",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

/**
 * Language is derived from the URL (English bare, Romanian under /ro) and
 * resolved in main.tsx before the app mounts, so it arrives here as a prop
 * rather than being held as state. It used to live in localStorage alone,
 * which is exactly why both languages shared one address and only English
 * was ever indexed — see lib/locale.ts.
 *
 * localStorage is still written, but it is now a *preference* rather than the
 * source of truth: it only decides where a visitor landing on the bare root
 * gets sent (see the redirect in App.tsx), and the URL always wins over it.
 */
export const LanguageProvider: React.FC<{ children: React.ReactNode; language: Language }> = ({ children, language }) => {
  useEffect(() => {
    try {
      window.localStorage.setItem("rostory_lang", language);
    } catch {
      // Ignore browser storage restrictions
    }
    if (typeof document !== "undefined") {
      document.documentElement.lang = language;
    }
  }, [language]);

  /**
   * Switching language is a navigation, not a state update: the same page in
   * the other locale is a different URL. Done as a full document load rather
   * than a client-side transition because the Router's basename is fixed at
   * mount — changing the prefix means rebuilding the router, and a reload is
   * both simpler and guaranteed correct. Language switching is a rare,
   * deliberate action, so the cost is acceptable.
   */
  const setLanguage = useCallback((next: Language) => {
    if (next === language) return;
    // Persist BEFORE navigating. The effect above only runs after the new
    // document mounts, so leaving it to that would mean the root redirect in
    // main.tsx reads the *old* preference on the way in and bounces the
    // reader straight back — an infinite loop between / and /ro.
    try {
      window.localStorage.setItem("rostory_lang", next);
    } catch {
      // Ignore browser storage restrictions
    }
    const { pathname, search, hash } = window.location;
    window.location.assign(localizedPath(next, stripLanguage(pathname)) + search + hash);
  }, [language]);

  const t = useCallback((key: TranslationKey) => {
    // Fall back to English when a key is missing in the active language so a
    // gap in one dictionary shows readable text instead of a blank. (Key
    // validity itself is enforced at compile time via TranslationKey.)
    const value = translations[language][key] ?? translations.en[key];
    if (value === undefined) {
      if (import.meta.env.DEV) {
        console.warn(`[i18n] Missing translation key: "${key}"`);
      }
      return '';
    }
    return value;
  }, [language]);

  // Stable identity so consumers don't re-render on unrelated provider
  // renders; `t` is memoized above for the same reason.
  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
